name: Build and Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - uses: actions/cache@v2
      name: Set up caches
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        pip install .

    - name: Build documentation
      run: |
        pdoc3 streamauc -o docs/ --html --force 
        mv docs/streamauc/* docs
        rmdir docs/streamauc
        
    - name: Generate sitemap.txt
      run: |
        BASE_URL="https://fabricioarendtorres.github.io/streamAUC/"
        find docs -name '*.html' | sed "s|docs/|${BASE_URL}|g" > docs/sitemap.txt

    - name: Generate robots.txt
      run: |
        echo "User-agent: *" > docs/robots.txt
        echo "Sitemap: https://fabricioarendtorres.github.io/streamAUC/sitemap.txt" >> docs/robots.txt

    # Upload for introspection, useful for pull requests and debugging
    - uses: actions/upload-artifact@v3
      with:
        name: generated-site
        path: docs/

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs
